-- =============================================================================
-- MIGRATION PATCH: Correção e alinhamento de colunas para associados, dependentes e contratos
-- Sistema ERAS PAX Taquari
-- =============================================================================

-- 1. TABELA: associados — Garante todas as colunas necessárias
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS tenant_id TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS empresa_id TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS cpf TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS rg TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS sexo TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS estado_civil TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS profissao TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS nome_pai TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS nome_mae TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS celular_whatsapp TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_cep TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS logradouro TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_logradouro TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_numero TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_bairro TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_cidade TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS uf TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS endereco_estado TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS tipo_pessoa TEXT DEFAULT 'PF';
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS tipo_associado TEXT DEFAULT 'titular';
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS plano_id TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS plano_pax_id UUID;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS plano_nome TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS numero_contrato TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS n_vidas INTEGER DEFAULT 1;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS valor_plano NUMERIC(10,2);
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS data_adesao DATE DEFAULT CURRENT_DATE;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS assinatura_base64 TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS documentos JSONB DEFAULT '[]';
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS historico_contratos JSONB DEFAULT '[]';
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ativo';
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE IF EXISTS associados ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. TABELA: dependentes — Garante todas as colunas necessárias
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS tenant_id TEXT;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS empresa_id TEXT;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS associado_id UUID;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS cpf TEXT;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS parentesco TEXT;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ativo';
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE IF EXISTS dependentes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 3. TABELA: contratos — Garante todas as colunas necessárias
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS tenant_id TEXT;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS empresa_id TEXT;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS associado_id UUID;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS plano_pax_id UUID;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS numero_contrato TEXT;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS data_inicio DATE DEFAULT CURRENT_DATE;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS data_adesao DATE DEFAULT CURRENT_DATE;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS data_vigencia DATE;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS data_fim DATE;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS valor_mensalidade NUMERIC(10,2) DEFAULT 0;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS taxa_adesao NUMERIC(10,2) DEFAULT 0;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS dia_vencimento INTEGER DEFAULT 10;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ativo';
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS forma_pagamento TEXT DEFAULT 'pix';
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE IF EXISTS contratos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 4. RLS Policies para garantir permissão completa aos usuários autenticados
ALTER TABLE associados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Usuários autenticados gerenciam associados" ON associados;
CREATE POLICY "Usuários autenticados gerenciam associados" ON associados FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE dependentes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Usuários autenticados gerenciam dependentes" ON dependentes;
CREATE POLICY "Usuários autenticados gerenciam dependentes" ON dependentes FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE contratos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Usuários autenticados gerenciam contratos" ON contratos;
CREATE POLICY "Usuários autenticados gerenciam contratos" ON contratos FOR ALL TO authenticated USING (true) WITH CHECK (true);
